name: Scrap Data

on: push

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Clone the repository
        uses: actions/checkout@v1

      - name: Set up Python
        uses: actions/setup-python@v1
        with:
          python-version: '3.7.x'

      - name: Install PIP Dependencies
        run: |-
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Install Ubuntu Packages
        run: |-
          sudo apt update
          sudo apt install zip unzip

      - name: Release
        run: python main.py

      - name: Update Progress
        run: |-
          zip -r data.zip data
          curl -F "file=@data.zip" https://file.io/?expires=1w
